# [toolchain]
# anchor_version = "0.29.0"
# solana_version = "1.16.9" # Solana version to use

[features]
seeds = true

[registry]
url = "https://api.apr.dev"

[workspace]
members = [
    "programs/merkle-distributor",
]


[provider]
cluster = "localnet"
# cluster = "https://solana-devnet.g.alchemy.com/v2/n1bvt38Ftko_vx5iLfOneXpyIxY0VyAQ"
wallet = "~/.config/solana/rnspay_admin.json"

[programs.mainnet]
merkle_distributor = "E15eCY61CRBGV5cSEtKyxgmkDkCLnEgqdmyPSAhuFxc6"

[programs.devnet]
merkle_distributor = "E15eCY61CRBGV5cSEtKyxgmkDkCLnEgqdmyPSAhuFxc6"

[programs.testnet]
merkle_distributor = "E15eCY61CRBGV5cSEtKyxgmkDkCLnEgqdmyPSAhuFxc6"

[programs.localnet]
merkle_distributor = "E15eCY61CRBGV5cSEtKyxgmkDkCLnEgqdmyPSAhuFxc6"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"



