edition = "2021"  # required by rust-analyzer
format_code_in_doc_comments = true
error_on_unformatted = false
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_indent = "Block"
